interface PokemonListInterface {
  id: number;
  display: string;
  thumbnail: string;
}

const pokemonList = function (): PokemonListInterface[] {
  // auto-generated via npm command, existing entries won't ever change, only newer ones will be added eventually
  return [
    { id: 1, display: "Bulbasaur", thumbnail: "sprites/pokemon/1.png" },
    { id: 2, display: "Ivysaur", thumbnail: "sprites/pokemon/2.png" },
    { id: 3, display: "Venusaur", thumbnail: "sprites/pokemon/3.png" },
    { id: 4, display: "Charmander", thumbnail: "sprites/pokemon/4.png" },
    { id: 5, display: "Charmeleon", thumbnail: "sprites/pokemon/5.png" },
    { id: 6, display: "Charizard", thumbnail: "sprites/pokemon/6.png" },
    { id: 7, display: "Squirtle", thumbnail: "sprites/pokemon/7.png" },
    { id: 8, display: "Wartortle", thumbnail: "sprites/pokemon/8.png" },
    { id: 9, display: "Blastoise", thumbnail: "sprites/pokemon/9.png" },
    { id: 10, display: "Caterpie", thumbnail: "sprites/pokemon/10.png" },
    { id: 11, display: "Metapod", thumbnail: "sprites/pokemon/11.png" },
    { id: 12, display: "Butterfree", thumbnail: "sprites/pokemon/12.png" },
    { id: 13, display: "Weedle", thumbnail: "sprites/pokemon/13.png" },
    { id: 14, display: "Kakuna", thumbnail: "sprites/pokemon/14.png" },
    { id: 15, display: "Beedrill", thumbnail: "sprites/pokemon/15.png" },
    { id: 16, display: "Pidgey", thumbnail: "sprites/pokemon/16.png" },
    { id: 17, display: "Pidgeotto", thumbnail: "sprites/pokemon/17.png" },
    { id: 18, display: "Pidgeot", thumbnail: "sprites/pokemon/18.png" },
    { id: 19, display: "Rattata", thumbnail: "sprites/pokemon/19.png" },
    { id: 20, display: "Raticate", thumbnail: "sprites/pokemon/20.png" },
    { id: 21, display: "Spearow", thumbnail: "sprites/pokemon/21.png" },
    { id: 22, display: "Fearow", thumbnail: "sprites/pokemon/22.png" },
    { id: 23, display: "Ekans", thumbnail: "sprites/pokemon/23.png" },
    { id: 24, display: "Arbok", thumbnail: "sprites/pokemon/24.png" },
    { id: 25, display: "Pikachu", thumbnail: "sprites/pokemon/25.png" },
    { id: 26, display: "Raichu", thumbnail: "sprites/pokemon/26.png" },
    { id: 27, display: "Sandshrew", thumbnail: "sprites/pokemon/27.png" },
    { id: 28, display: "Sandslash", thumbnail: "sprites/pokemon/28.png" },
    { id: 29, display: "Nidoran-F", thumbnail: "sprites/pokemon/29.png" },
    { id: 30, display: "Nidorina", thumbnail: "sprites/pokemon/30.png" },
    { id: 31, display: "Nidoqueen", thumbnail: "sprites/pokemon/31.png" },
    { id: 32, display: "Nidoran-M", thumbnail: "sprites/pokemon/32.png" },
    { id: 33, display: "Nidorino", thumbnail: "sprites/pokemon/33.png" },
    { id: 34, display: "Nidoking", thumbnail: "sprites/pokemon/34.png" },
    { id: 35, display: "Clefairy", thumbnail: "sprites/pokemon/35.png" },
    { id: 36, display: "Clefable", thumbnail: "sprites/pokemon/36.png" },
    { id: 37, display: "Vulpix", thumbnail: "sprites/pokemon/37.png" },
    { id: 38, display: "Ninetales", thumbnail: "sprites/pokemon/38.png" },
    { id: 39, display: "Jigglypuff", thumbnail: "sprites/pokemon/39.png" },
    { id: 40, display: "Wigglytuff", thumbnail: "sprites/pokemon/40.png" },
    { id: 41, display: "Zubat", thumbnail: "sprites/pokemon/41.png" },
    { id: 42, display: "Golbat", thumbnail: "sprites/pokemon/42.png" },
    { id: 43, display: "Oddish", thumbnail: "sprites/pokemon/43.png" },
    { id: 44, display: "Gloom", thumbnail: "sprites/pokemon/44.png" },
    { id: 45, display: "Vileplume", thumbnail: "sprites/pokemon/45.png" },
    { id: 46, display: "Paras", thumbnail: "sprites/pokemon/46.png" },
    { id: 47, display: "Parasect", thumbnail: "sprites/pokemon/47.png" },
    { id: 48, display: "Venonat", thumbnail: "sprites/pokemon/48.png" },
    { id: 49, display: "Venomoth", thumbnail: "sprites/pokemon/49.png" },
    { id: 50, display: "Diglett", thumbnail: "sprites/pokemon/50.png" },
    { id: 51, display: "Dugtrio", thumbnail: "sprites/pokemon/51.png" },
    { id: 52, display: "Meowth", thumbnail: "sprites/pokemon/52.png" },
    { id: 53, display: "Persian", thumbnail: "sprites/pokemon/53.png" },
    { id: 54, display: "Psyduck", thumbnail: "sprites/pokemon/54.png" },
    { id: 55, display: "Golduck", thumbnail: "sprites/pokemon/55.png" },
    { id: 56, display: "Mankey", thumbnail: "sprites/pokemon/56.png" },
    { id: 57, display: "Primeape", thumbnail: "sprites/pokemon/57.png" },
    { id: 58, display: "Growlithe", thumbnail: "sprites/pokemon/58.png" },
    { id: 59, display: "Arcanine", thumbnail: "sprites/pokemon/59.png" },
    { id: 60, display: "Poliwag", thumbnail: "sprites/pokemon/60.png" },
    { id: 61, display: "Poliwhirl", thumbnail: "sprites/pokemon/61.png" },
    { id: 62, display: "Poliwrath", thumbnail: "sprites/pokemon/62.png" },
    { id: 63, display: "Abra", thumbnail: "sprites/pokemon/63.png" },
    { id: 64, display: "Kadabra", thumbnail: "sprites/pokemon/64.png" },
    { id: 65, display: "Alakazam", thumbnail: "sprites/pokemon/65.png" },
    { id: 66, display: "Machop", thumbnail: "sprites/pokemon/66.png" },
    { id: 67, display: "Machoke", thumbnail: "sprites/pokemon/67.png" },
    { id: 68, display: "Machamp", thumbnail: "sprites/pokemon/68.png" },
    { id: 69, display: "Bellsprout", thumbnail: "sprites/pokemon/69.png" },
    { id: 70, display: "Weepinbell", thumbnail: "sprites/pokemon/70.png" },
    { id: 71, display: "Victreebel", thumbnail: "sprites/pokemon/71.png" },
    { id: 72, display: "Tentacool", thumbnail: "sprites/pokemon/72.png" },
    { id: 73, display: "Tentacruel", thumbnail: "sprites/pokemon/73.png" },
    { id: 74, display: "Geodude", thumbnail: "sprites/pokemon/74.png" },
    { id: 75, display: "Graveler", thumbnail: "sprites/pokemon/75.png" },
    { id: 76, display: "Golem", thumbnail: "sprites/pokemon/76.png" },
    { id: 77, display: "Ponyta", thumbnail: "sprites/pokemon/77.png" },
    { id: 78, display: "Rapidash", thumbnail: "sprites/pokemon/78.png" },
    { id: 79, display: "Slowpoke", thumbnail: "sprites/pokemon/79.png" },
    { id: 80, display: "Slowbro", thumbnail: "sprites/pokemon/80.png" },
    { id: 81, display: "Magnemite", thumbnail: "sprites/pokemon/81.png" },
    { id: 82, display: "Magneton", thumbnail: "sprites/pokemon/82.png" },
    { id: 83, display: "Farfetchd", thumbnail: "sprites/pokemon/83.png" },
    { id: 84, display: "Doduo", thumbnail: "sprites/pokemon/84.png" },
    { id: 85, display: "Dodrio", thumbnail: "sprites/pokemon/85.png" },
    { id: 86, display: "Seel", thumbnail: "sprites/pokemon/86.png" },
    { id: 87, display: "Dewgong", thumbnail: "sprites/pokemon/87.png" },
    { id: 88, display: "Grimer", thumbnail: "sprites/pokemon/88.png" },
    { id: 89, display: "Muk", thumbnail: "sprites/pokemon/89.png" },
    { id: 90, display: "Shellder", thumbnail: "sprites/pokemon/90.png" },
    { id: 91, display: "Cloyster", thumbnail: "sprites/pokemon/91.png" },
    { id: 92, display: "Gastly", thumbnail: "sprites/pokemon/92.png" },
    { id: 93, display: "Haunter", thumbnail: "sprites/pokemon/93.png" },
    { id: 94, display: "Gengar", thumbnail: "sprites/pokemon/94.png" },
    { id: 95, display: "Onix", thumbnail: "sprites/pokemon/95.png" },
    { id: 96, display: "Drowzee", thumbnail: "sprites/pokemon/96.png" },
    { id: 97, display: "Hypno", thumbnail: "sprites/pokemon/97.png" },
    { id: 98, display: "Krabby", thumbnail: "sprites/pokemon/98.png" },
    { id: 99, display: "Kingler", thumbnail: "sprites/pokemon/99.png" },
    { id: 100, display: "Voltorb", thumbnail: "sprites/pokemon/100.png" },
    { id: 101, display: "Electrode", thumbnail: "sprites/pokemon/101.png" },
    { id: 102, display: "Exeggcute", thumbnail: "sprites/pokemon/102.png" },
    { id: 103, display: "Exeggutor", thumbnail: "sprites/pokemon/103.png" },
    { id: 104, display: "Cubone", thumbnail: "sprites/pokemon/104.png" },
    { id: 105, display: "Marowak", thumbnail: "sprites/pokemon/105.png" },
    { id: 106, display: "Hitmonlee", thumbnail: "sprites/pokemon/106.png" },
    { id: 107, display: "Hitmonchan", thumbnail: "sprites/pokemon/107.png" },
    { id: 108, display: "Lickitung", thumbnail: "sprites/pokemon/108.png" },
    { id: 109, display: "Koffing", thumbnail: "sprites/pokemon/109.png" },
    { id: 110, display: "Weezing", thumbnail: "sprites/pokemon/110.png" },
    { id: 111, display: "Rhyhorn", thumbnail: "sprites/pokemon/111.png" },
    { id: 112, display: "Rhydon", thumbnail: "sprites/pokemon/112.png" },
    { id: 113, display: "Chansey", thumbnail: "sprites/pokemon/113.png" },
    { id: 114, display: "Tangela", thumbnail: "sprites/pokemon/114.png" },
    { id: 115, display: "Kangaskhan", thumbnail: "sprites/pokemon/115.png" },
    { id: 116, display: "Horsea", thumbnail: "sprites/pokemon/116.png" },
    { id: 117, display: "Seadra", thumbnail: "sprites/pokemon/117.png" },
    { id: 118, display: "Goldeen", thumbnail: "sprites/pokemon/118.png" },
    { id: 119, display: "Seaking", thumbnail: "sprites/pokemon/119.png" },
    { id: 120, display: "Staryu", thumbnail: "sprites/pokemon/120.png" },
    { id: 121, display: "Starmie", thumbnail: "sprites/pokemon/121.png" },
    { id: 122, display: "Mr-Mime", thumbnail: "sprites/pokemon/122.png" },
    { id: 123, display: "Scyther", thumbnail: "sprites/pokemon/123.png" },
    { id: 124, display: "Jynx", thumbnail: "sprites/pokemon/124.png" },
    { id: 125, display: "Electabuzz", thumbnail: "sprites/pokemon/125.png" },
    { id: 126, display: "Magmar", thumbnail: "sprites/pokemon/126.png" },
    { id: 127, display: "Pinsir", thumbnail: "sprites/pokemon/127.png" },
    { id: 128, display: "Tauros", thumbnail: "sprites/pokemon/128.png" },
    { id: 129, display: "Magikarp", thumbnail: "sprites/pokemon/129.png" },
    { id: 130, display: "Gyarados", thumbnail: "sprites/pokemon/130.png" },
    { id: 131, display: "Lapras", thumbnail: "sprites/pokemon/131.png" },
    { id: 132, display: "Ditto", thumbnail: "sprites/pokemon/132.png" },
    { id: 133, display: "Eevee", thumbnail: "sprites/pokemon/133.png" },
    { id: 134, display: "Vaporeon", thumbnail: "sprites/pokemon/134.png" },
    { id: 135, display: "Jolteon", thumbnail: "sprites/pokemon/135.png" },
    { id: 136, display: "Flareon", thumbnail: "sprites/pokemon/136.png" },
    { id: 137, display: "Porygon", thumbnail: "sprites/pokemon/137.png" },
    { id: 138, display: "Omanyte", thumbnail: "sprites/pokemon/138.png" },
    { id: 139, display: "Omastar", thumbnail: "sprites/pokemon/139.png" },
    { id: 140, display: "Kabuto", thumbnail: "sprites/pokemon/140.png" },
    { id: 141, display: "Kabutops", thumbnail: "sprites/pokemon/141.png" },
    { id: 142, display: "Aerodactyl", thumbnail: "sprites/pokemon/142.png" },
    { id: 143, display: "Snorlax", thumbnail: "sprites/pokemon/143.png" },
    { id: 144, display: "Articuno", thumbnail: "sprites/pokemon/144.png" },
    { id: 145, display: "Zapdos", thumbnail: "sprites/pokemon/145.png" },
    { id: 146, display: "Moltres", thumbnail: "sprites/pokemon/146.png" },
    { id: 147, display: "Dratini", thumbnail: "sprites/pokemon/147.png" },
    { id: 148, display: "Dragonair", thumbnail: "sprites/pokemon/148.png" },
    { id: 149, display: "Dragonite", thumbnail: "sprites/pokemon/149.png" },
    { id: 150, display: "Mewtwo", thumbnail: "sprites/pokemon/150.png" },
    { id: 151, display: "Mew", thumbnail: "sprites/pokemon/151.png" },
    { id: 152, display: "Chikorita", thumbnail: "sprites/pokemon/152.png" },
    { id: 153, display: "Bayleef", thumbnail: "sprites/pokemon/153.png" },
    { id: 154, display: "Meganium", thumbnail: "sprites/pokemon/154.png" },
    { id: 155, display: "Cyndaquil", thumbnail: "sprites/pokemon/155.png" },
    { id: 156, display: "Quilava", thumbnail: "sprites/pokemon/156.png" },
    { id: 157, display: "Typhlosion", thumbnail: "sprites/pokemon/157.png" },
    { id: 158, display: "Totodile", thumbnail: "sprites/pokemon/158.png" },
    { id: 159, display: "Croconaw", thumbnail: "sprites/pokemon/159.png" },
    { id: 160, display: "Feraligatr", thumbnail: "sprites/pokemon/160.png" },
    { id: 161, display: "Sentret", thumbnail: "sprites/pokemon/161.png" },
    { id: 162, display: "Furret", thumbnail: "sprites/pokemon/162.png" },
    { id: 163, display: "Hoothoot", thumbnail: "sprites/pokemon/163.png" },
    { id: 164, display: "Noctowl", thumbnail: "sprites/pokemon/164.png" },
    { id: 165, display: "Ledyba", thumbnail: "sprites/pokemon/165.png" },
    { id: 166, display: "Ledian", thumbnail: "sprites/pokemon/166.png" },
    { id: 167, display: "Spinarak", thumbnail: "sprites/pokemon/167.png" },
    { id: 168, display: "Ariados", thumbnail: "sprites/pokemon/168.png" },
    { id: 169, display: "Crobat", thumbnail: "sprites/pokemon/169.png" },
    { id: 170, display: "Chinchou", thumbnail: "sprites/pokemon/170.png" },
    { id: 171, display: "Lanturn", thumbnail: "sprites/pokemon/171.png" },
    { id: 172, display: "Pichu", thumbnail: "sprites/pokemon/172.png" },
    { id: 173, display: "Cleffa", thumbnail: "sprites/pokemon/173.png" },
    { id: 174, display: "Igglybuff", thumbnail: "sprites/pokemon/174.png" },
    { id: 175, display: "Togepi", thumbnail: "sprites/pokemon/175.png" },
    { id: 176, display: "Togetic", thumbnail: "sprites/pokemon/176.png" },
    { id: 177, display: "Natu", thumbnail: "sprites/pokemon/177.png" },
    { id: 178, display: "Xatu", thumbnail: "sprites/pokemon/178.png" },
    { id: 179, display: "Mareep", thumbnail: "sprites/pokemon/179.png" },
    { id: 180, display: "Flaaffy", thumbnail: "sprites/pokemon/180.png" },
    { id: 181, display: "Ampharos", thumbnail: "sprites/pokemon/181.png" },
    { id: 182, display: "Bellossom", thumbnail: "sprites/pokemon/182.png" },
    { id: 183, display: "Marill", thumbnail: "sprites/pokemon/183.png" },
    { id: 184, display: "Azumarill", thumbnail: "sprites/pokemon/184.png" },
    { id: 185, display: "Sudowoodo", thumbnail: "sprites/pokemon/185.png" },
    { id: 186, display: "Politoed", thumbnail: "sprites/pokemon/186.png" },
    { id: 187, display: "Hoppip", thumbnail: "sprites/pokemon/187.png" },
    { id: 188, display: "Skiploom", thumbnail: "sprites/pokemon/188.png" },
    { id: 189, display: "Jumpluff", thumbnail: "sprites/pokemon/189.png" },
    { id: 190, display: "Aipom", thumbnail: "sprites/pokemon/190.png" },
    { id: 191, display: "Sunkern", thumbnail: "sprites/pokemon/191.png" },
    { id: 192, display: "Sunflora", thumbnail: "sprites/pokemon/192.png" },
    { id: 193, display: "Yanma", thumbnail: "sprites/pokemon/193.png" },
    { id: 194, display: "Wooper", thumbnail: "sprites/pokemon/194.png" },
    { id: 195, display: "Quagsire", thumbnail: "sprites/pokemon/195.png" },
    { id: 196, display: "Espeon", thumbnail: "sprites/pokemon/196.png" },
    { id: 197, display: "Umbreon", thumbnail: "sprites/pokemon/197.png" },
    { id: 198, display: "Murkrow", thumbnail: "sprites/pokemon/198.png" },
    { id: 199, display: "Slowking", thumbnail: "sprites/pokemon/199.png" },
    { id: 200, display: "Misdreavus", thumbnail: "sprites/pokemon/200.png" },
    { id: 201, display: "Unown", thumbnail: "sprites/pokemon/201.png" },
    { id: 202, display: "Wobbuffet", thumbnail: "sprites/pokemon/202.png" },
    { id: 203, display: "Girafarig", thumbnail: "sprites/pokemon/203.png" },
    { id: 204, display: "Pineco", thumbnail: "sprites/pokemon/204.png" },
    { id: 205, display: "Forretress", thumbnail: "sprites/pokemon/205.png" },
    { id: 206, display: "Dunsparce", thumbnail: "sprites/pokemon/206.png" },
    { id: 207, display: "Gligar", thumbnail: "sprites/pokemon/207.png" },
    { id: 208, display: "Steelix", thumbnail: "sprites/pokemon/208.png" },
    { id: 209, display: "Snubbull", thumbnail: "sprites/pokemon/209.png" },
    { id: 210, display: "Granbull", thumbnail: "sprites/pokemon/210.png" },
    { id: 211, display: "Qwilfish", thumbnail: "sprites/pokemon/211.png" },
    { id: 212, display: "Scizor", thumbnail: "sprites/pokemon/212.png" },
    { id: 213, display: "Shuckle", thumbnail: "sprites/pokemon/213.png" },
    { id: 214, display: "Heracross", thumbnail: "sprites/pokemon/214.png" },
    { id: 215, display: "Sneasel", thumbnail: "sprites/pokemon/215.png" },
    { id: 216, display: "Teddiursa", thumbnail: "sprites/pokemon/216.png" },
    { id: 217, display: "Ursaring", thumbnail: "sprites/pokemon/217.png" },
    { id: 218, display: "Slugma", thumbnail: "sprites/pokemon/218.png" },
    { id: 219, display: "Magcargo", thumbnail: "sprites/pokemon/219.png" },
    { id: 220, display: "Swinub", thumbnail: "sprites/pokemon/220.png" },
    { id: 221, display: "Piloswine", thumbnail: "sprites/pokemon/221.png" },
    { id: 222, display: "Corsola", thumbnail: "sprites/pokemon/222.png" },
    { id: 223, display: "Remoraid", thumbnail: "sprites/pokemon/223.png" },
    { id: 224, display: "Octillery", thumbnail: "sprites/pokemon/224.png" },
    { id: 225, display: "Delibird", thumbnail: "sprites/pokemon/225.png" },
    { id: 226, display: "Mantine", thumbnail: "sprites/pokemon/226.png" },
    { id: 227, display: "Skarmory", thumbnail: "sprites/pokemon/227.png" },
    { id: 228, display: "Houndour", thumbnail: "sprites/pokemon/228.png" },
    { id: 229, display: "Houndoom", thumbnail: "sprites/pokemon/229.png" },
    { id: 230, display: "Kingdra", thumbnail: "sprites/pokemon/230.png" },
    { id: 231, display: "Phanpy", thumbnail: "sprites/pokemon/231.png" },
    { id: 232, display: "Donphan", thumbnail: "sprites/pokemon/232.png" },
    { id: 233, display: "Porygon2", thumbnail: "sprites/pokemon/233.png" },
    { id: 234, display: "Stantler", thumbnail: "sprites/pokemon/234.png" },
    { id: 235, display: "Smeargle", thumbnail: "sprites/pokemon/235.png" },
    { id: 236, display: "Tyrogue", thumbnail: "sprites/pokemon/236.png" },
    { id: 237, display: "Hitmontop", thumbnail: "sprites/pokemon/237.png" },
    { id: 238, display: "Smoochum", thumbnail: "sprites/pokemon/238.png" },
    { id: 239, display: "Elekid", thumbnail: "sprites/pokemon/239.png" },
    { id: 240, display: "Magby", thumbnail: "sprites/pokemon/240.png" },
    { id: 241, display: "Miltank", thumbnail: "sprites/pokemon/241.png" },
    { id: 242, display: "Blissey", thumbnail: "sprites/pokemon/242.png" },
    { id: 243, display: "Raikou", thumbnail: "sprites/pokemon/243.png" },
    { id: 244, display: "Entei", thumbnail: "sprites/pokemon/244.png" },
    { id: 245, display: "Suicune", thumbnail: "sprites/pokemon/245.png" },
    { id: 246, display: "Larvitar", thumbnail: "sprites/pokemon/246.png" },
    { id: 247, display: "Pupitar", thumbnail: "sprites/pokemon/247.png" },
    { id: 248, display: "Tyranitar", thumbnail: "sprites/pokemon/248.png" },
    { id: 249, display: "Lugia", thumbnail: "sprites/pokemon/249.png" },
    { id: 250, display: "Ho-Oh", thumbnail: "sprites/pokemon/250.png" },
    { id: 251, display: "Celebi", thumbnail: "sprites/pokemon/251.png" },
    { id: 252, display: "Treecko", thumbnail: "sprites/pokemon/252.png" },
    { id: 253, display: "Grovyle", thumbnail: "sprites/pokemon/253.png" },
    { id: 254, display: "Sceptile", thumbnail: "sprites/pokemon/254.png" },
    { id: 255, display: "Torchic", thumbnail: "sprites/pokemon/255.png" },
    { id: 256, display: "Combusken", thumbnail: "sprites/pokemon/256.png" },
    { id: 257, display: "Blaziken", thumbnail: "sprites/pokemon/257.png" },
    { id: 258, display: "Mudkip", thumbnail: "sprites/pokemon/258.png" },
    { id: 259, display: "Marshtomp", thumbnail: "sprites/pokemon/259.png" },
    { id: 260, display: "Swampert", thumbnail: "sprites/pokemon/260.png" },
    { id: 261, display: "Poochyena", thumbnail: "sprites/pokemon/261.png" },
    { id: 262, display: "Mightyena", thumbnail: "sprites/pokemon/262.png" },
    { id: 263, display: "Zigzagoon", thumbnail: "sprites/pokemon/263.png" },
    { id: 264, display: "Linoone", thumbnail: "sprites/pokemon/264.png" },
    { id: 265, display: "Wurmple", thumbnail: "sprites/pokemon/265.png" },
    { id: 266, display: "Silcoon", thumbnail: "sprites/pokemon/266.png" },
    { id: 267, display: "Beautifly", thumbnail: "sprites/pokemon/267.png" },
    { id: 268, display: "Cascoon", thumbnail: "sprites/pokemon/268.png" },
    { id: 269, display: "Dustox", thumbnail: "sprites/pokemon/269.png" },
    { id: 270, display: "Lotad", thumbnail: "sprites/pokemon/270.png" },
    { id: 271, display: "Lombre", thumbnail: "sprites/pokemon/271.png" },
    { id: 272, display: "Ludicolo", thumbnail: "sprites/pokemon/272.png" },
    { id: 273, display: "Seedot", thumbnail: "sprites/pokemon/273.png" },
    { id: 274, display: "Nuzleaf", thumbnail: "sprites/pokemon/274.png" },
    { id: 275, display: "Shiftry", thumbnail: "sprites/pokemon/275.png" },
    { id: 276, display: "Taillow", thumbnail: "sprites/pokemon/276.png" },
    { id: 277, display: "Swellow", thumbnail: "sprites/pokemon/277.png" },
    { id: 278, display: "Wingull", thumbnail: "sprites/pokemon/278.png" },
    { id: 279, display: "Pelipper", thumbnail: "sprites/pokemon/279.png" },
    { id: 280, display: "Ralts", thumbnail: "sprites/pokemon/280.png" },
    { id: 281, display: "Kirlia", thumbnail: "sprites/pokemon/281.png" },
    { id: 282, display: "Gardevoir", thumbnail: "sprites/pokemon/282.png" },
    { id: 283, display: "Surskit", thumbnail: "sprites/pokemon/283.png" },
    { id: 284, display: "Masquerain", thumbnail: "sprites/pokemon/284.png" },
    { id: 285, display: "Shroomish", thumbnail: "sprites/pokemon/285.png" },
    { id: 286, display: "Breloom", thumbnail: "sprites/pokemon/286.png" },
    { id: 287, display: "Slakoth", thumbnail: "sprites/pokemon/287.png" },
    { id: 288, display: "Vigoroth", thumbnail: "sprites/pokemon/288.png" },
    { id: 289, display: "Slaking", thumbnail: "sprites/pokemon/289.png" },
    { id: 290, display: "Nincada", thumbnail: "sprites/pokemon/290.png" },
    { id: 291, display: "Ninjask", thumbnail: "sprites/pokemon/291.png" },
    { id: 292, display: "Shedinja", thumbnail: "sprites/pokemon/292.png" },
    { id: 293, display: "Whismur", thumbnail: "sprites/pokemon/293.png" },
    { id: 294, display: "Loudred", thumbnail: "sprites/pokemon/294.png" },
    { id: 295, display: "Exploud", thumbnail: "sprites/pokemon/295.png" },
    { id: 296, display: "Makuhita", thumbnail: "sprites/pokemon/296.png" },
    { id: 297, display: "Hariyama", thumbnail: "sprites/pokemon/297.png" },
    { id: 298, display: "Azurill", thumbnail: "sprites/pokemon/298.png" },
    { id: 299, display: "Nosepass", thumbnail: "sprites/pokemon/299.png" },
    { id: 300, display: "Skitty", thumbnail: "sprites/pokemon/300.png" },
    { id: 301, display: "Delcatty", thumbnail: "sprites/pokemon/301.png" },
    { id: 302, display: "Sableye", thumbnail: "sprites/pokemon/302.png" },
    { id: 303, display: "Mawile", thumbnail: "sprites/pokemon/303.png" },
    { id: 304, display: "Aron", thumbnail: "sprites/pokemon/304.png" },
    { id: 305, display: "Lairon", thumbnail: "sprites/pokemon/305.png" },
    { id: 306, display: "Aggron", thumbnail: "sprites/pokemon/306.png" },
    { id: 307, display: "Meditite", thumbnail: "sprites/pokemon/307.png" },
    { id: 308, display: "Medicham", thumbnail: "sprites/pokemon/308.png" },
    { id: 309, display: "Electrike", thumbnail: "sprites/pokemon/309.png" },
    { id: 310, display: "Manectric", thumbnail: "sprites/pokemon/310.png" },
    { id: 311, display: "Plusle", thumbnail: "sprites/pokemon/311.png" },
    { id: 312, display: "Minun", thumbnail: "sprites/pokemon/312.png" },
    { id: 313, display: "Volbeat", thumbnail: "sprites/pokemon/313.png" },
    { id: 314, display: "Illumise", thumbnail: "sprites/pokemon/314.png" },
    { id: 315, display: "Roselia", thumbnail: "sprites/pokemon/315.png" },
    { id: 316, display: "Gulpin", thumbnail: "sprites/pokemon/316.png" },
    { id: 317, display: "Swalot", thumbnail: "sprites/pokemon/317.png" },
    { id: 318, display: "Carvanha", thumbnail: "sprites/pokemon/318.png" },
    { id: 319, display: "Sharpedo", thumbnail: "sprites/pokemon/319.png" },
    { id: 320, display: "Wailmer", thumbnail: "sprites/pokemon/320.png" },
    { id: 321, display: "Wailord", thumbnail: "sprites/pokemon/321.png" },
    { id: 322, display: "Numel", thumbnail: "sprites/pokemon/322.png" },
    { id: 323, display: "Camerupt", thumbnail: "sprites/pokemon/323.png" },
    { id: 324, display: "Torkoal", thumbnail: "sprites/pokemon/324.png" },
    { id: 325, display: "Spoink", thumbnail: "sprites/pokemon/325.png" },
    { id: 326, display: "Grumpig", thumbnail: "sprites/pokemon/326.png" },
    { id: 327, display: "Spinda", thumbnail: "sprites/pokemon/327.png" },
    { id: 328, display: "Trapinch", thumbnail: "sprites/pokemon/328.png" },
    { id: 329, display: "Vibrava", thumbnail: "sprites/pokemon/329.png" },
    { id: 330, display: "Flygon", thumbnail: "sprites/pokemon/330.png" },
    { id: 331, display: "Cacnea", thumbnail: "sprites/pokemon/331.png" },
    { id: 332, display: "Cacturne", thumbnail: "sprites/pokemon/332.png" },
    { id: 333, display: "Swablu", thumbnail: "sprites/pokemon/333.png" },
    { id: 334, display: "Altaria", thumbnail: "sprites/pokemon/334.png" },
    { id: 335, display: "Zangoose", thumbnail: "sprites/pokemon/335.png" },
    { id: 336, display: "Seviper", thumbnail: "sprites/pokemon/336.png" },
    { id: 337, display: "Lunatone", thumbnail: "sprites/pokemon/337.png" },
    { id: 338, display: "Solrock", thumbnail: "sprites/pokemon/338.png" },
    { id: 339, display: "Barboach", thumbnail: "sprites/pokemon/339.png" },
    { id: 340, display: "Whiscash", thumbnail: "sprites/pokemon/340.png" },
    { id: 341, display: "Corphish", thumbnail: "sprites/pokemon/341.png" },
    { id: 342, display: "Crawdaunt", thumbnail: "sprites/pokemon/342.png" },
    { id: 343, display: "Baltoy", thumbnail: "sprites/pokemon/343.png" },
    { id: 344, display: "Claydol", thumbnail: "sprites/pokemon/344.png" },
    { id: 345, display: "Lileep", thumbnail: "sprites/pokemon/345.png" },
    { id: 346, display: "Cradily", thumbnail: "sprites/pokemon/346.png" },
    { id: 347, display: "Anorith", thumbnail: "sprites/pokemon/347.png" },
    { id: 348, display: "Armaldo", thumbnail: "sprites/pokemon/348.png" },
    { id: 349, display: "Feebas", thumbnail: "sprites/pokemon/349.png" },
    { id: 350, display: "Milotic", thumbnail: "sprites/pokemon/350.png" },
    { id: 351, display: "Castform", thumbnail: "sprites/pokemon/351.png" },
    { id: 352, display: "Kecleon", thumbnail: "sprites/pokemon/352.png" },
    { id: 353, display: "Shuppet", thumbnail: "sprites/pokemon/353.png" },
    { id: 354, display: "Banette", thumbnail: "sprites/pokemon/354.png" },
    { id: 355, display: "Duskull", thumbnail: "sprites/pokemon/355.png" },
    { id: 356, display: "Dusclops", thumbnail: "sprites/pokemon/356.png" },
    { id: 357, display: "Tropius", thumbnail: "sprites/pokemon/357.png" },
    { id: 358, display: "Chimecho", thumbnail: "sprites/pokemon/358.png" },
    { id: 359, display: "Absol", thumbnail: "sprites/pokemon/359.png" },
    { id: 360, display: "Wynaut", thumbnail: "sprites/pokemon/360.png" },
    { id: 361, display: "Snorunt", thumbnail: "sprites/pokemon/361.png" },
    { id: 362, display: "Glalie", thumbnail: "sprites/pokemon/362.png" },
    { id: 363, display: "Spheal", thumbnail: "sprites/pokemon/363.png" },
    { id: 364, display: "Sealeo", thumbnail: "sprites/pokemon/364.png" },
    { id: 365, display: "Walrein", thumbnail: "sprites/pokemon/365.png" },
    { id: 366, display: "Clamperl", thumbnail: "sprites/pokemon/366.png" },
    { id: 367, display: "Huntail", thumbnail: "sprites/pokemon/367.png" },
    { id: 368, display: "Gorebyss", thumbnail: "sprites/pokemon/368.png" },
    { id: 369, display: "Relicanth", thumbnail: "sprites/pokemon/369.png" },
    { id: 370, display: "Luvdisc", thumbnail: "sprites/pokemon/370.png" },
    { id: 371, display: "Bagon", thumbnail: "sprites/pokemon/371.png" },
    { id: 372, display: "Shelgon", thumbnail: "sprites/pokemon/372.png" },
    { id: 373, display: "Salamence", thumbnail: "sprites/pokemon/373.png" },
    { id: 374, display: "Beldum", thumbnail: "sprites/pokemon/374.png" },
    { id: 375, display: "Metang", thumbnail: "sprites/pokemon/375.png" },
    { id: 376, display: "Metagross", thumbnail: "sprites/pokemon/376.png" },
    { id: 377, display: "Regirock", thumbnail: "sprites/pokemon/377.png" },
    { id: 378, display: "Regice", thumbnail: "sprites/pokemon/378.png" },
    { id: 379, display: "Registeel", thumbnail: "sprites/pokemon/379.png" },
    { id: 380, display: "Latias", thumbnail: "sprites/pokemon/380.png" },
    { id: 381, display: "Latios", thumbnail: "sprites/pokemon/381.png" },
    { id: 382, display: "Kyogre", thumbnail: "sprites/pokemon/382.png" },
    { id: 383, display: "Groudon", thumbnail: "sprites/pokemon/383.png" },
    { id: 384, display: "Rayquaza", thumbnail: "sprites/pokemon/384.png" },
    { id: 385, display: "Jirachi", thumbnail: "sprites/pokemon/385.png" },
    { id: 386, display: "Deoxys-Normal", thumbnail: "sprites/pokemon/386.png" },
    { id: 387, display: "Turtwig", thumbnail: "sprites/pokemon/387.png" },
    { id: 388, display: "Grotle", thumbnail: "sprites/pokemon/388.png" },
    { id: 389, display: "Torterra", thumbnail: "sprites/pokemon/389.png" },
    { id: 390, display: "Chimchar", thumbnail: "sprites/pokemon/390.png" },
    { id: 391, display: "Monferno", thumbnail: "sprites/pokemon/391.png" },
    { id: 392, display: "Infernape", thumbnail: "sprites/pokemon/392.png" },
    { id: 393, display: "Piplup", thumbnail: "sprites/pokemon/393.png" },
    { id: 394, display: "Prinplup", thumbnail: "sprites/pokemon/394.png" },
    { id: 395, display: "Empoleon", thumbnail: "sprites/pokemon/395.png" },
    { id: 396, display: "Starly", thumbnail: "sprites/pokemon/396.png" },
    { id: 397, display: "Staravia", thumbnail: "sprites/pokemon/397.png" },
    { id: 398, display: "Staraptor", thumbnail: "sprites/pokemon/398.png" },
    { id: 399, display: "Bidoof", thumbnail: "sprites/pokemon/399.png" },
    { id: 400, display: "Bibarel", thumbnail: "sprites/pokemon/400.png" },
    { id: 401, display: "Kricketot", thumbnail: "sprites/pokemon/401.png" },
    { id: 402, display: "Kricketune", thumbnail: "sprites/pokemon/402.png" },
    { id: 403, display: "Shinx", thumbnail: "sprites/pokemon/403.png" },
    { id: 404, display: "Luxio", thumbnail: "sprites/pokemon/404.png" },
    { id: 405, display: "Luxray", thumbnail: "sprites/pokemon/405.png" },
    { id: 406, display: "Budew", thumbnail: "sprites/pokemon/406.png" },
    { id: 407, display: "Roserade", thumbnail: "sprites/pokemon/407.png" },
    { id: 408, display: "Cranidos", thumbnail: "sprites/pokemon/408.png" },
    { id: 409, display: "Rampardos", thumbnail: "sprites/pokemon/409.png" },
    { id: 410, display: "Shieldon", thumbnail: "sprites/pokemon/410.png" },
    { id: 411, display: "Bastiodon", thumbnail: "sprites/pokemon/411.png" },
    { id: 412, display: "Burmy", thumbnail: "sprites/pokemon/412.png" },
    {
      id: 413,
      display: "Wormadam-Plant",
      thumbnail: "sprites/pokemon/413.png",
    },
    { id: 414, display: "Mothim", thumbnail: "sprites/pokemon/414.png" },
    { id: 415, display: "Combee", thumbnail: "sprites/pokemon/415.png" },
    { id: 416, display: "Vespiquen", thumbnail: "sprites/pokemon/416.png" },
    { id: 417, display: "Pachirisu", thumbnail: "sprites/pokemon/417.png" },
    { id: 418, display: "Buizel", thumbnail: "sprites/pokemon/418.png" },
    { id: 419, display: "Floatzel", thumbnail: "sprites/pokemon/419.png" },
    { id: 420, display: "Cherubi", thumbnail: "sprites/pokemon/420.png" },
    { id: 421, display: "Cherrim", thumbnail: "sprites/pokemon/421.png" },
    { id: 422, display: "Shellos", thumbnail: "sprites/pokemon/422.png" },
    { id: 423, display: "Gastrodon", thumbnail: "sprites/pokemon/423.png" },
    { id: 424, display: "Ambipom", thumbnail: "sprites/pokemon/424.png" },
    { id: 425, display: "Drifloon", thumbnail: "sprites/pokemon/425.png" },
    { id: 426, display: "Drifblim", thumbnail: "sprites/pokemon/426.png" },
    { id: 427, display: "Buneary", thumbnail: "sprites/pokemon/427.png" },
    { id: 428, display: "Lopunny", thumbnail: "sprites/pokemon/428.png" },
    { id: 429, display: "Mismagius", thumbnail: "sprites/pokemon/429.png" },
    { id: 430, display: "Honchkrow", thumbnail: "sprites/pokemon/430.png" },
    { id: 431, display: "Glameow", thumbnail: "sprites/pokemon/431.png" },
    { id: 432, display: "Purugly", thumbnail: "sprites/pokemon/432.png" },
    { id: 433, display: "Chingling", thumbnail: "sprites/pokemon/433.png" },
    { id: 434, display: "Stunky", thumbnail: "sprites/pokemon/434.png" },
    { id: 435, display: "Skuntank", thumbnail: "sprites/pokemon/435.png" },
    { id: 436, display: "Bronzor", thumbnail: "sprites/pokemon/436.png" },
    { id: 437, display: "Bronzong", thumbnail: "sprites/pokemon/437.png" },
    { id: 438, display: "Bonsly", thumbnail: "sprites/pokemon/438.png" },
    { id: 439, display: "Mime-Jr", thumbnail: "sprites/pokemon/439.png" },
    { id: 440, display: "Happiny", thumbnail: "sprites/pokemon/440.png" },
    { id: 441, display: "Chatot", thumbnail: "sprites/pokemon/441.png" },
    { id: 442, display: "Spiritomb", thumbnail: "sprites/pokemon/442.png" },
    { id: 443, display: "Gible", thumbnail: "sprites/pokemon/443.png" },
    { id: 444, display: "Gabite", thumbnail: "sprites/pokemon/444.png" },
    { id: 445, display: "Garchomp", thumbnail: "sprites/pokemon/445.png" },
    { id: 446, display: "Munchlax", thumbnail: "sprites/pokemon/446.png" },
    { id: 447, display: "Riolu", thumbnail: "sprites/pokemon/447.png" },
    { id: 448, display: "Lucario", thumbnail: "sprites/pokemon/448.png" },
    { id: 449, display: "Hippopotas", thumbnail: "sprites/pokemon/449.png" },
    { id: 450, display: "Hippowdon", thumbnail: "sprites/pokemon/450.png" },
    { id: 451, display: "Skorupi", thumbnail: "sprites/pokemon/451.png" },
    { id: 452, display: "Drapion", thumbnail: "sprites/pokemon/452.png" },
    { id: 453, display: "Croagunk", thumbnail: "sprites/pokemon/453.png" },
    { id: 454, display: "Toxicroak", thumbnail: "sprites/pokemon/454.png" },
    { id: 455, display: "Carnivine", thumbnail: "sprites/pokemon/455.png" },
    { id: 456, display: "Finneon", thumbnail: "sprites/pokemon/456.png" },
    { id: 457, display: "Lumineon", thumbnail: "sprites/pokemon/457.png" },
    { id: 458, display: "Mantyke", thumbnail: "sprites/pokemon/458.png" },
    { id: 459, display: "Snover", thumbnail: "sprites/pokemon/459.png" },
    { id: 460, display: "Abomasnow", thumbnail: "sprites/pokemon/460.png" },
    { id: 461, display: "Weavile", thumbnail: "sprites/pokemon/461.png" },
    { id: 462, display: "Magnezone", thumbnail: "sprites/pokemon/462.png" },
    { id: 463, display: "Lickilicky", thumbnail: "sprites/pokemon/463.png" },
    { id: 464, display: "Rhyperior", thumbnail: "sprites/pokemon/464.png" },
    { id: 465, display: "Tangrowth", thumbnail: "sprites/pokemon/465.png" },
    { id: 466, display: "Electivire", thumbnail: "sprites/pokemon/466.png" },
    { id: 467, display: "Magmortar", thumbnail: "sprites/pokemon/467.png" },
    { id: 468, display: "Togekiss", thumbnail: "sprites/pokemon/468.png" },
    { id: 469, display: "Yanmega", thumbnail: "sprites/pokemon/469.png" },
    { id: 470, display: "Leafeon", thumbnail: "sprites/pokemon/470.png" },
    { id: 471, display: "Glaceon", thumbnail: "sprites/pokemon/471.png" },
    { id: 472, display: "Gliscor", thumbnail: "sprites/pokemon/472.png" },
    { id: 473, display: "Mamoswine", thumbnail: "sprites/pokemon/473.png" },
    { id: 474, display: "Porygon-Z", thumbnail: "sprites/pokemon/474.png" },
    { id: 475, display: "Gallade", thumbnail: "sprites/pokemon/475.png" },
    { id: 476, display: "Probopass", thumbnail: "sprites/pokemon/476.png" },
    { id: 477, display: "Dusknoir", thumbnail: "sprites/pokemon/477.png" },
    { id: 478, display: "Froslass", thumbnail: "sprites/pokemon/478.png" },
    { id: 479, display: "Rotom", thumbnail: "sprites/pokemon/479.png" },
    { id: 480, display: "Uxie", thumbnail: "sprites/pokemon/480.png" },
    { id: 481, display: "Mesprit", thumbnail: "sprites/pokemon/481.png" },
    { id: 482, display: "Azelf", thumbnail: "sprites/pokemon/482.png" },
    { id: 483, display: "Dialga", thumbnail: "sprites/pokemon/483.png" },
    { id: 484, display: "Palkia", thumbnail: "sprites/pokemon/484.png" },
    { id: 485, display: "Heatran", thumbnail: "sprites/pokemon/485.png" },
    { id: 486, display: "Regigigas", thumbnail: "sprites/pokemon/486.png" },
    {
      id: 487,
      display: "Giratina-Altered",
      thumbnail: "sprites/pokemon/487.png",
    },
    { id: 488, display: "Cresselia", thumbnail: "sprites/pokemon/488.png" },
    { id: 489, display: "Phione", thumbnail: "sprites/pokemon/489.png" },
    { id: 490, display: "Manaphy", thumbnail: "sprites/pokemon/490.png" },
    { id: 491, display: "Darkrai", thumbnail: "sprites/pokemon/491.png" },
    { id: 492, display: "Shaymin-Land", thumbnail: "sprites/pokemon/492.png" },
    { id: 493, display: "Arceus", thumbnail: "sprites/pokemon/493.png" },
    { id: 494, display: "Victini", thumbnail: "sprites/pokemon/494.png" },
    { id: 495, display: "Snivy", thumbnail: "sprites/pokemon/495.png" },
    { id: 496, display: "Servine", thumbnail: "sprites/pokemon/496.png" },
    { id: 497, display: "Serperior", thumbnail: "sprites/pokemon/497.png" },
    { id: 498, display: "Tepig", thumbnail: "sprites/pokemon/498.png" },
    { id: 499, display: "Pignite", thumbnail: "sprites/pokemon/499.png" },
    { id: 500, display: "Emboar", thumbnail: "sprites/pokemon/500.png" },
    { id: 501, display: "Oshawott", thumbnail: "sprites/pokemon/501.png" },
    { id: 502, display: "Dewott", thumbnail: "sprites/pokemon/502.png" },
    { id: 503, display: "Samurott", thumbnail: "sprites/pokemon/503.png" },
    { id: 504, display: "Patrat", thumbnail: "sprites/pokemon/504.png" },
    { id: 505, display: "Watchog", thumbnail: "sprites/pokemon/505.png" },
    { id: 506, display: "Lillipup", thumbnail: "sprites/pokemon/506.png" },
    { id: 507, display: "Herdier", thumbnail: "sprites/pokemon/507.png" },
    { id: 508, display: "Stoutland", thumbnail: "sprites/pokemon/508.png" },
    { id: 509, display: "Purrloin", thumbnail: "sprites/pokemon/509.png" },
    { id: 510, display: "Liepard", thumbnail: "sprites/pokemon/510.png" },
    { id: 511, display: "Pansage", thumbnail: "sprites/pokemon/511.png" },
    { id: 512, display: "Simisage", thumbnail: "sprites/pokemon/512.png" },
    { id: 513, display: "Pansear", thumbnail: "sprites/pokemon/513.png" },
    { id: 514, display: "Simisear", thumbnail: "sprites/pokemon/514.png" },
    { id: 515, display: "Panpour", thumbnail: "sprites/pokemon/515.png" },
    { id: 516, display: "Simipour", thumbnail: "sprites/pokemon/516.png" },
    { id: 517, display: "Munna", thumbnail: "sprites/pokemon/517.png" },
    { id: 518, display: "Musharna", thumbnail: "sprites/pokemon/518.png" },
    { id: 519, display: "Pidove", thumbnail: "sprites/pokemon/519.png" },
    { id: 520, display: "Tranquill", thumbnail: "sprites/pokemon/520.png" },
    { id: 521, display: "Unfezant", thumbnail: "sprites/pokemon/521.png" },
    { id: 522, display: "Blitzle", thumbnail: "sprites/pokemon/522.png" },
    { id: 523, display: "Zebstrika", thumbnail: "sprites/pokemon/523.png" },
    { id: 524, display: "Roggenrola", thumbnail: "sprites/pokemon/524.png" },
    { id: 525, display: "Boldore", thumbnail: "sprites/pokemon/525.png" },
    { id: 526, display: "Gigalith", thumbnail: "sprites/pokemon/526.png" },
    { id: 527, display: "Woobat", thumbnail: "sprites/pokemon/527.png" },
    { id: 528, display: "Swoobat", thumbnail: "sprites/pokemon/528.png" },
    { id: 529, display: "Drilbur", thumbnail: "sprites/pokemon/529.png" },
    { id: 530, display: "Excadrill", thumbnail: "sprites/pokemon/530.png" },
    { id: 531, display: "Audino", thumbnail: "sprites/pokemon/531.png" },
    { id: 532, display: "Timburr", thumbnail: "sprites/pokemon/532.png" },
    { id: 533, display: "Gurdurr", thumbnail: "sprites/pokemon/533.png" },
    { id: 534, display: "Conkeldurr", thumbnail: "sprites/pokemon/534.png" },
    { id: 535, display: "Tympole", thumbnail: "sprites/pokemon/535.png" },
    { id: 536, display: "Palpitoad", thumbnail: "sprites/pokemon/536.png" },
    { id: 537, display: "Seismitoad", thumbnail: "sprites/pokemon/537.png" },
    { id: 538, display: "Throh", thumbnail: "sprites/pokemon/538.png" },
    { id: 539, display: "Sawk", thumbnail: "sprites/pokemon/539.png" },
    { id: 540, display: "Sewaddle", thumbnail: "sprites/pokemon/540.png" },
    { id: 541, display: "Swadloon", thumbnail: "sprites/pokemon/541.png" },
    { id: 542, display: "Leavanny", thumbnail: "sprites/pokemon/542.png" },
    { id: 543, display: "Venipede", thumbnail: "sprites/pokemon/543.png" },
    { id: 544, display: "Whirlipede", thumbnail: "sprites/pokemon/544.png" },
    { id: 545, display: "Scolipede", thumbnail: "sprites/pokemon/545.png" },
    { id: 546, display: "Cottonee", thumbnail: "sprites/pokemon/546.png" },
    { id: 547, display: "Whimsicott", thumbnail: "sprites/pokemon/547.png" },
    { id: 548, display: "Petilil", thumbnail: "sprites/pokemon/548.png" },
    { id: 549, display: "Lilligant", thumbnail: "sprites/pokemon/549.png" },
    {
      id: 550,
      display: "Basculin-Red-Striped",
      thumbnail: "sprites/pokemon/550.png",
    },
    { id: 551, display: "Sandile", thumbnail: "sprites/pokemon/551.png" },
    { id: 552, display: "Krokorok", thumbnail: "sprites/pokemon/552.png" },
    { id: 553, display: "Krookodile", thumbnail: "sprites/pokemon/553.png" },
    { id: 554, display: "Darumaka", thumbnail: "sprites/pokemon/554.png" },
    {
      id: 555,
      display: "Darmanitan-Standard",
      thumbnail: "sprites/pokemon/555.png",
    },
    { id: 556, display: "Maractus", thumbnail: "sprites/pokemon/556.png" },
    { id: 557, display: "Dwebble", thumbnail: "sprites/pokemon/557.png" },
    { id: 558, display: "Crustle", thumbnail: "sprites/pokemon/558.png" },
    { id: 559, display: "Scraggy", thumbnail: "sprites/pokemon/559.png" },
    { id: 560, display: "Scrafty", thumbnail: "sprites/pokemon/560.png" },
    { id: 561, display: "Sigilyph", thumbnail: "sprites/pokemon/561.png" },
    { id: 562, display: "Yamask", thumbnail: "sprites/pokemon/562.png" },
    { id: 563, display: "Cofagrigus", thumbnail: "sprites/pokemon/563.png" },
    { id: 564, display: "Tirtouga", thumbnail: "sprites/pokemon/564.png" },
    { id: 565, display: "Carracosta", thumbnail: "sprites/pokemon/565.png" },
    { id: 566, display: "Archen", thumbnail: "sprites/pokemon/566.png" },
    { id: 567, display: "Archeops", thumbnail: "sprites/pokemon/567.png" },
    { id: 568, display: "Trubbish", thumbnail: "sprites/pokemon/568.png" },
    { id: 569, display: "Garbodor", thumbnail: "sprites/pokemon/569.png" },
    { id: 570, display: "Zorua", thumbnail: "sprites/pokemon/570.png" },
    { id: 571, display: "Zoroark", thumbnail: "sprites/pokemon/571.png" },
    { id: 572, display: "Minccino", thumbnail: "sprites/pokemon/572.png" },
    { id: 573, display: "Cinccino", thumbnail: "sprites/pokemon/573.png" },
    { id: 574, display: "Gothita", thumbnail: "sprites/pokemon/574.png" },
    { id: 575, display: "Gothorita", thumbnail: "sprites/pokemon/575.png" },
    { id: 576, display: "Gothitelle", thumbnail: "sprites/pokemon/576.png" },
    { id: 577, display: "Solosis", thumbnail: "sprites/pokemon/577.png" },
    { id: 578, display: "Duosion", thumbnail: "sprites/pokemon/578.png" },
    { id: 579, display: "Reuniclus", thumbnail: "sprites/pokemon/579.png" },
    { id: 580, display: "Ducklett", thumbnail: "sprites/pokemon/580.png" },
    { id: 581, display: "Swanna", thumbnail: "sprites/pokemon/581.png" },
    { id: 582, display: "Vanillite", thumbnail: "sprites/pokemon/582.png" },
    { id: 583, display: "Vanillish", thumbnail: "sprites/pokemon/583.png" },
    { id: 584, display: "Vanilluxe", thumbnail: "sprites/pokemon/584.png" },
    { id: 585, display: "Deerling", thumbnail: "sprites/pokemon/585.png" },
    { id: 586, display: "Sawsbuck", thumbnail: "sprites/pokemon/586.png" },
    { id: 587, display: "Emolga", thumbnail: "sprites/pokemon/587.png" },
    { id: 588, display: "Karrablast", thumbnail: "sprites/pokemon/588.png" },
    { id: 589, display: "Escavalier", thumbnail: "sprites/pokemon/589.png" },
    { id: 590, display: "Foongus", thumbnail: "sprites/pokemon/590.png" },
    { id: 591, display: "Amoonguss", thumbnail: "sprites/pokemon/591.png" },
    { id: 592, display: "Frillish", thumbnail: "sprites/pokemon/592.png" },
    { id: 593, display: "Jellicent", thumbnail: "sprites/pokemon/593.png" },
    { id: 594, display: "Alomomola", thumbnail: "sprites/pokemon/594.png" },
    { id: 595, display: "Joltik", thumbnail: "sprites/pokemon/595.png" },
    { id: 596, display: "Galvantula", thumbnail: "sprites/pokemon/596.png" },
    { id: 597, display: "Ferroseed", thumbnail: "sprites/pokemon/597.png" },
    { id: 598, display: "Ferrothorn", thumbnail: "sprites/pokemon/598.png" },
    { id: 599, display: "Klink", thumbnail: "sprites/pokemon/599.png" },
    { id: 600, display: "Klang", thumbnail: "sprites/pokemon/600.png" },
    { id: 601, display: "Klinklang", thumbnail: "sprites/pokemon/601.png" },
    { id: 602, display: "Tynamo", thumbnail: "sprites/pokemon/602.png" },
    { id: 603, display: "Eelektrik", thumbnail: "sprites/pokemon/603.png" },
    { id: 604, display: "Eelektross", thumbnail: "sprites/pokemon/604.png" },
    { id: 605, display: "Elgyem", thumbnail: "sprites/pokemon/605.png" },
    { id: 606, display: "Beheeyem", thumbnail: "sprites/pokemon/606.png" },
    { id: 607, display: "Litwick", thumbnail: "sprites/pokemon/607.png" },
    { id: 608, display: "Lampent", thumbnail: "sprites/pokemon/608.png" },
    { id: 609, display: "Chandelure", thumbnail: "sprites/pokemon/609.png" },
    { id: 610, display: "Axew", thumbnail: "sprites/pokemon/610.png" },
    { id: 611, display: "Fraxure", thumbnail: "sprites/pokemon/611.png" },
    { id: 612, display: "Haxorus", thumbnail: "sprites/pokemon/612.png" },
    { id: 613, display: "Cubchoo", thumbnail: "sprites/pokemon/613.png" },
    { id: 614, display: "Beartic", thumbnail: "sprites/pokemon/614.png" },
    { id: 615, display: "Cryogonal", thumbnail: "sprites/pokemon/615.png" },
    { id: 616, display: "Shelmet", thumbnail: "sprites/pokemon/616.png" },
    { id: 617, display: "Accelgor", thumbnail: "sprites/pokemon/617.png" },
    { id: 618, display: "Stunfisk", thumbnail: "sprites/pokemon/618.png" },
    { id: 619, display: "Mienfoo", thumbnail: "sprites/pokemon/619.png" },
    { id: 620, display: "Mienshao", thumbnail: "sprites/pokemon/620.png" },
    { id: 621, display: "Druddigon", thumbnail: "sprites/pokemon/621.png" },
    { id: 622, display: "Golett", thumbnail: "sprites/pokemon/622.png" },
    { id: 623, display: "Golurk", thumbnail: "sprites/pokemon/623.png" },
    { id: 624, display: "Pawniard", thumbnail: "sprites/pokemon/624.png" },
    { id: 625, display: "Bisharp", thumbnail: "sprites/pokemon/625.png" },
    { id: 626, display: "Bouffalant", thumbnail: "sprites/pokemon/626.png" },
    { id: 627, display: "Rufflet", thumbnail: "sprites/pokemon/627.png" },
    { id: 628, display: "Braviary", thumbnail: "sprites/pokemon/628.png" },
    { id: 629, display: "Vullaby", thumbnail: "sprites/pokemon/629.png" },
    { id: 630, display: "Mandibuzz", thumbnail: "sprites/pokemon/630.png" },
    { id: 631, display: "Heatmor", thumbnail: "sprites/pokemon/631.png" },
    { id: 632, display: "Durant", thumbnail: "sprites/pokemon/632.png" },
    { id: 633, display: "Deino", thumbnail: "sprites/pokemon/633.png" },
    { id: 634, display: "Zweilous", thumbnail: "sprites/pokemon/634.png" },
    { id: 635, display: "Hydreigon", thumbnail: "sprites/pokemon/635.png" },
    { id: 636, display: "Larvesta", thumbnail: "sprites/pokemon/636.png" },
    { id: 637, display: "Volcarona", thumbnail: "sprites/pokemon/637.png" },
    { id: 638, display: "Cobalion", thumbnail: "sprites/pokemon/638.png" },
    { id: 639, display: "Terrakion", thumbnail: "sprites/pokemon/639.png" },
    { id: 640, display: "Virizion", thumbnail: "sprites/pokemon/640.png" },
    {
      id: 641,
      display: "Tornadus-Incarnate",
      thumbnail: "sprites/pokemon/641.png",
    },
    {
      id: 642,
      display: "Thundurus-Incarnate",
      thumbnail: "sprites/pokemon/642.png",
    },
    { id: 643, display: "Reshiram", thumbnail: "sprites/pokemon/643.png" },
    { id: 644, display: "Zekrom", thumbnail: "sprites/pokemon/644.png" },
    {
      id: 645,
      display: "Landorus-Incarnate",
      thumbnail: "sprites/pokemon/645.png",
    },
    { id: 646, display: "Kyurem", thumbnail: "sprites/pokemon/646.png" },
    {
      id: 647,
      display: "Keldeo-Ordinary",
      thumbnail: "sprites/pokemon/647.png",
    },
    { id: 648, display: "Meloetta-Aria", thumbnail: "sprites/pokemon/648.png" },
    { id: 649, display: "Genesect", thumbnail: "sprites/pokemon/649.png" },
    { id: 650, display: "Chespin", thumbnail: "sprites/pokemon/650.png" },
    { id: 651, display: "Quilladin", thumbnail: "sprites/pokemon/651.png" },
    { id: 652, display: "Chesnaught", thumbnail: "sprites/pokemon/652.png" },
    { id: 653, display: "Fennekin", thumbnail: "sprites/pokemon/653.png" },
    { id: 654, display: "Braixen", thumbnail: "sprites/pokemon/654.png" },
    { id: 655, display: "Delphox", thumbnail: "sprites/pokemon/655.png" },
    { id: 656, display: "Froakie", thumbnail: "sprites/pokemon/656.png" },
    { id: 657, display: "Frogadier", thumbnail: "sprites/pokemon/657.png" },
    { id: 658, display: "Greninja", thumbnail: "sprites/pokemon/658.png" },
    { id: 659, display: "Bunnelby", thumbnail: "sprites/pokemon/659.png" },
    { id: 660, display: "Diggersby", thumbnail: "sprites/pokemon/660.png" },
    { id: 661, display: "Fletchling", thumbnail: "sprites/pokemon/661.png" },
    { id: 662, display: "Fletchinder", thumbnail: "sprites/pokemon/662.png" },
    { id: 663, display: "Talonflame", thumbnail: "sprites/pokemon/663.png" },
    { id: 664, display: "Scatterbug", thumbnail: "sprites/pokemon/664.png" },
    { id: 665, display: "Spewpa", thumbnail: "sprites/pokemon/665.png" },
    { id: 666, display: "Vivillon", thumbnail: "sprites/pokemon/666.png" },
    { id: 667, display: "Litleo", thumbnail: "sprites/pokemon/667.png" },
    { id: 668, display: "Pyroar", thumbnail: "sprites/pokemon/668.png" },
    { id: 669, display: "Flabebe", thumbnail: "sprites/pokemon/669.png" },
    { id: 670, display: "Floette", thumbnail: "sprites/pokemon/670.png" },
    { id: 671, display: "Florges", thumbnail: "sprites/pokemon/671.png" },
    { id: 672, display: "Skiddo", thumbnail: "sprites/pokemon/672.png" },
    { id: 673, display: "Gogoat", thumbnail: "sprites/pokemon/673.png" },
    { id: 674, display: "Pancham", thumbnail: "sprites/pokemon/674.png" },
    { id: 675, display: "Pangoro", thumbnail: "sprites/pokemon/675.png" },
    { id: 676, display: "Furfrou", thumbnail: "sprites/pokemon/676.png" },
    { id: 677, display: "Espurr", thumbnail: "sprites/pokemon/677.png" },
    { id: 678, display: "Meowstic-Male", thumbnail: "sprites/pokemon/678.png" },
    { id: 679, display: "Honedge", thumbnail: "sprites/pokemon/679.png" },
    { id: 680, display: "Doublade", thumbnail: "sprites/pokemon/680.png" },
    {
      id: 681,
      display: "Aegislash-Shield",
      thumbnail: "sprites/pokemon/681.png",
    },
    { id: 682, display: "Spritzee", thumbnail: "sprites/pokemon/682.png" },
    { id: 683, display: "Aromatisse", thumbnail: "sprites/pokemon/683.png" },
    { id: 684, display: "Swirlix", thumbnail: "sprites/pokemon/684.png" },
    { id: 685, display: "Slurpuff", thumbnail: "sprites/pokemon/685.png" },
    { id: 686, display: "Inkay", thumbnail: "sprites/pokemon/686.png" },
    { id: 687, display: "Malamar", thumbnail: "sprites/pokemon/687.png" },
    { id: 688, display: "Binacle", thumbnail: "sprites/pokemon/688.png" },
    { id: 689, display: "Barbaracle", thumbnail: "sprites/pokemon/689.png" },
    { id: 690, display: "Skrelp", thumbnail: "sprites/pokemon/690.png" },
    { id: 691, display: "Dragalge", thumbnail: "sprites/pokemon/691.png" },
    { id: 692, display: "Clauncher", thumbnail: "sprites/pokemon/692.png" },
    { id: 693, display: "Clawitzer", thumbnail: "sprites/pokemon/693.png" },
    { id: 694, display: "Helioptile", thumbnail: "sprites/pokemon/694.png" },
    { id: 695, display: "Heliolisk", thumbnail: "sprites/pokemon/695.png" },
    { id: 696, display: "Tyrunt", thumbnail: "sprites/pokemon/696.png" },
    { id: 697, display: "Tyrantrum", thumbnail: "sprites/pokemon/697.png" },
    { id: 698, display: "Amaura", thumbnail: "sprites/pokemon/698.png" },
    { id: 699, display: "Aurorus", thumbnail: "sprites/pokemon/699.png" },
    { id: 700, display: "Sylveon", thumbnail: "sprites/pokemon/700.png" },
    { id: 701, display: "Hawlucha", thumbnail: "sprites/pokemon/701.png" },
    { id: 702, display: "Dedenne", thumbnail: "sprites/pokemon/702.png" },
    { id: 703, display: "Carbink", thumbnail: "sprites/pokemon/703.png" },
    { id: 704, display: "Goomy", thumbnail: "sprites/pokemon/704.png" },
    { id: 705, display: "Sliggoo", thumbnail: "sprites/pokemon/705.png" },
    { id: 706, display: "Goodra", thumbnail: "sprites/pokemon/706.png" },
    { id: 707, display: "Klefki", thumbnail: "sprites/pokemon/707.png" },
    { id: 708, display: "Phantump", thumbnail: "sprites/pokemon/708.png" },
    { id: 709, display: "Trevenant", thumbnail: "sprites/pokemon/709.png" },
    {
      id: 710,
      display: "Pumpkaboo-Average",
      thumbnail: "sprites/pokemon/710.png",
    },
    {
      id: 711,
      display: "Gourgeist-Average",
      thumbnail: "sprites/pokemon/711.png",
    },
    { id: 712, display: "Bergmite", thumbnail: "sprites/pokemon/712.png" },
    { id: 713, display: "Avalugg", thumbnail: "sprites/pokemon/713.png" },
    { id: 714, display: "Noibat", thumbnail: "sprites/pokemon/714.png" },
    { id: 715, display: "Noivern", thumbnail: "sprites/pokemon/715.png" },
    { id: 716, display: "Xerneas", thumbnail: "sprites/pokemon/716.png" },
    { id: 717, display: "Yveltal", thumbnail: "sprites/pokemon/717.png" },
    { id: 718, display: "Zygarde-50", thumbnail: "sprites/pokemon/718.png" },
    { id: 719, display: "Diancie", thumbnail: "sprites/pokemon/719.png" },
    { id: 720, display: "Hoopa", thumbnail: "sprites/pokemon/720.png" },
    { id: 721, display: "Volcanion", thumbnail: "sprites/pokemon/721.png" },
    { id: 722, display: "Rowlet", thumbnail: "sprites/pokemon/722.png" },
    { id: 723, display: "Dartrix", thumbnail: "sprites/pokemon/723.png" },
    { id: 724, display: "Decidueye", thumbnail: "sprites/pokemon/724.png" },
    { id: 725, display: "Litten", thumbnail: "sprites/pokemon/725.png" },
    { id: 726, display: "Torracat", thumbnail: "sprites/pokemon/726.png" },
    { id: 727, display: "Incineroar", thumbnail: "sprites/pokemon/727.png" },
    { id: 728, display: "Popplio", thumbnail: "sprites/pokemon/728.png" },
    { id: 729, display: "Brionne", thumbnail: "sprites/pokemon/729.png" },
    { id: 730, display: "Primarina", thumbnail: "sprites/pokemon/730.png" },
    { id: 731, display: "Pikipek", thumbnail: "sprites/pokemon/731.png" },
    { id: 732, display: "Trumbeak", thumbnail: "sprites/pokemon/732.png" },
    { id: 733, display: "Toucannon", thumbnail: "sprites/pokemon/733.png" },
    { id: 734, display: "Yungoos", thumbnail: "sprites/pokemon/734.png" },
    { id: 735, display: "Gumshoos", thumbnail: "sprites/pokemon/735.png" },
    { id: 736, display: "Grubbin", thumbnail: "sprites/pokemon/736.png" },
    { id: 737, display: "Charjabug", thumbnail: "sprites/pokemon/737.png" },
    { id: 738, display: "Vikavolt", thumbnail: "sprites/pokemon/738.png" },
    { id: 739, display: "Crabrawler", thumbnail: "sprites/pokemon/739.png" },
    { id: 740, display: "Crabominable", thumbnail: "sprites/pokemon/740.png" },
    {
      id: 741,
      display: "Oricorio-Baile",
      thumbnail: "sprites/pokemon/741.png",
    },
    { id: 742, display: "Cutiefly", thumbnail: "sprites/pokemon/742.png" },
    { id: 743, display: "Ribombee", thumbnail: "sprites/pokemon/743.png" },
    { id: 744, display: "Rockruff", thumbnail: "sprites/pokemon/744.png" },
    {
      id: 745,
      display: "Lycanroc-Midday",
      thumbnail: "sprites/pokemon/745.png",
    },
    {
      id: 746,
      display: "Wishiwashi-Solo",
      thumbnail: "sprites/pokemon/746.png",
    },
    { id: 747, display: "Mareanie", thumbnail: "sprites/pokemon/747.png" },
    { id: 748, display: "Toxapex", thumbnail: "sprites/pokemon/748.png" },
    { id: 749, display: "Mudbray", thumbnail: "sprites/pokemon/749.png" },
    { id: 750, display: "Mudsdale", thumbnail: "sprites/pokemon/750.png" },
    { id: 751, display: "Dewpider", thumbnail: "sprites/pokemon/751.png" },
    { id: 752, display: "Araquanid", thumbnail: "sprites/pokemon/752.png" },
    { id: 753, display: "Fomantis", thumbnail: "sprites/pokemon/753.png" },
    { id: 754, display: "Lurantis", thumbnail: "sprites/pokemon/754.png" },
    { id: 755, display: "Morelull", thumbnail: "sprites/pokemon/755.png" },
    { id: 756, display: "Shiinotic", thumbnail: "sprites/pokemon/756.png" },
    { id: 757, display: "Salandit", thumbnail: "sprites/pokemon/757.png" },
    { id: 758, display: "Salazzle", thumbnail: "sprites/pokemon/758.png" },
    { id: 759, display: "Stufful", thumbnail: "sprites/pokemon/759.png" },
    { id: 760, display: "Bewear", thumbnail: "sprites/pokemon/760.png" },
    { id: 761, display: "Bounsweet", thumbnail: "sprites/pokemon/761.png" },
    { id: 762, display: "Steenee", thumbnail: "sprites/pokemon/762.png" },
    { id: 763, display: "Tsareena", thumbnail: "sprites/pokemon/763.png" },
    { id: 764, display: "Comfey", thumbnail: "sprites/pokemon/764.png" },
    { id: 765, display: "Oranguru", thumbnail: "sprites/pokemon/765.png" },
    { id: 766, display: "Passimian", thumbnail: "sprites/pokemon/766.png" },
    { id: 767, display: "Wimpod", thumbnail: "sprites/pokemon/767.png" },
    { id: 768, display: "Golisopod", thumbnail: "sprites/pokemon/768.png" },
    { id: 769, display: "Sandygast", thumbnail: "sprites/pokemon/769.png" },
    { id: 770, display: "Palossand", thumbnail: "sprites/pokemon/770.png" },
    { id: 771, display: "Pyukumuku", thumbnail: "sprites/pokemon/771.png" },
    { id: 772, display: "Type-Null", thumbnail: "sprites/pokemon/772.png" },
    { id: 773, display: "Silvally", thumbnail: "sprites/pokemon/773.png" },
    {
      id: 774,
      display: "Minior-Red-Meteor",
      thumbnail: "sprites/pokemon/774.png",
    },
    { id: 775, display: "Komala", thumbnail: "sprites/pokemon/775.png" },
    { id: 776, display: "Turtonator", thumbnail: "sprites/pokemon/776.png" },
    { id: 777, display: "Togedemaru", thumbnail: "sprites/pokemon/777.png" },
    {
      id: 778,
      display: "Mimikyu-Disguised",
      thumbnail: "sprites/pokemon/778.png",
    },
    { id: 779, display: "Bruxish", thumbnail: "sprites/pokemon/779.png" },
    { id: 780, display: "Drampa", thumbnail: "sprites/pokemon/780.png" },
    { id: 781, display: "Dhelmise", thumbnail: "sprites/pokemon/781.png" },
    { id: 782, display: "Jangmo-O", thumbnail: "sprites/pokemon/782.png" },
    { id: 783, display: "Hakamo-O", thumbnail: "sprites/pokemon/783.png" },
    { id: 784, display: "Kommo-O", thumbnail: "sprites/pokemon/784.png" },
    { id: 785, display: "Tapu-Koko", thumbnail: "sprites/pokemon/785.png" },
    { id: 786, display: "Tapu-Lele", thumbnail: "sprites/pokemon/786.png" },
    { id: 787, display: "Tapu-Bulu", thumbnail: "sprites/pokemon/787.png" },
    { id: 788, display: "Tapu-Fini", thumbnail: "sprites/pokemon/788.png" },
    { id: 789, display: "Cosmog", thumbnail: "sprites/pokemon/789.png" },
    { id: 790, display: "Cosmoem", thumbnail: "sprites/pokemon/790.png" },
    { id: 791, display: "Solgaleo", thumbnail: "sprites/pokemon/791.png" },
    { id: 792, display: "Lunala", thumbnail: "sprites/pokemon/792.png" },
    { id: 793, display: "Nihilego", thumbnail: "sprites/pokemon/793.png" },
    { id: 794, display: "Buzzwole", thumbnail: "sprites/pokemon/794.png" },
    { id: 795, display: "Pheromosa", thumbnail: "sprites/pokemon/795.png" },
    { id: 796, display: "Xurkitree", thumbnail: "sprites/pokemon/796.png" },
    { id: 797, display: "Celesteela", thumbnail: "sprites/pokemon/797.png" },
    { id: 798, display: "Kartana", thumbnail: "sprites/pokemon/798.png" },
    { id: 799, display: "Guzzlord", thumbnail: "sprites/pokemon/799.png" },
    { id: 800, display: "Necrozma", thumbnail: "sprites/pokemon/800.png" },
    { id: 801, display: "Magearna", thumbnail: "sprites/pokemon/801.png" },
    { id: 802, display: "Marshadow", thumbnail: "sprites/pokemon/802.png" },
    { id: 803, display: "Poipole", thumbnail: "sprites/pokemon/803.png" },
    { id: 804, display: "Naganadel", thumbnail: "sprites/pokemon/804.png" },
    { id: 805, display: "Stakataka", thumbnail: "sprites/pokemon/805.png" },
    { id: 806, display: "Blacephalon", thumbnail: "sprites/pokemon/806.png" },
    { id: 807, display: "Zeraora", thumbnail: "sprites/pokemon/807.png" },
    { id: 808, display: "Meltan", thumbnail: "sprites/pokemon/808.png" },
    { id: 809, display: "Melmetal", thumbnail: "sprites/pokemon/809.png" },
    { id: 810, display: "Grookey", thumbnail: "sprites/pokemon/810.png" },
    { id: 811, display: "Thwackey", thumbnail: "sprites/pokemon/811.png" },
    { id: 812, display: "Rillaboom", thumbnail: "sprites/pokemon/812.png" },
    { id: 813, display: "Scorbunny", thumbnail: "sprites/pokemon/813.png" },
    { id: 814, display: "Raboot", thumbnail: "sprites/pokemon/814.png" },
    { id: 815, display: "Cinderace", thumbnail: "sprites/pokemon/815.png" },
    { id: 816, display: "Sobble", thumbnail: "sprites/pokemon/816.png" },
    { id: 817, display: "Drizzile", thumbnail: "sprites/pokemon/817.png" },
    { id: 818, display: "Inteleon", thumbnail: "sprites/pokemon/818.png" },
    { id: 819, display: "Skwovet", thumbnail: "sprites/pokemon/819.png" },
    { id: 820, display: "Greedent", thumbnail: "sprites/pokemon/820.png" },
    { id: 821, display: "Rookidee", thumbnail: "sprites/pokemon/821.png" },
    { id: 822, display: "Corvisquire", thumbnail: "sprites/pokemon/822.png" },
    { id: 823, display: "Corviknight", thumbnail: "sprites/pokemon/823.png" },
    { id: 824, display: "Blipbug", thumbnail: "sprites/pokemon/824.png" },
    { id: 825, display: "Dottler", thumbnail: "sprites/pokemon/825.png" },
    { id: 826, display: "Orbeetle", thumbnail: "sprites/pokemon/826.png" },
    { id: 827, display: "Nickit", thumbnail: "sprites/pokemon/827.png" },
    { id: 828, display: "Thievul", thumbnail: "sprites/pokemon/828.png" },
    { id: 829, display: "Gossifleur", thumbnail: "sprites/pokemon/829.png" },
    { id: 830, display: "Eldegoss", thumbnail: "sprites/pokemon/830.png" },
    { id: 831, display: "Wooloo", thumbnail: "sprites/pokemon/831.png" },
    { id: 832, display: "Dubwool", thumbnail: "sprites/pokemon/832.png" },
    { id: 833, display: "Chewtle", thumbnail: "sprites/pokemon/833.png" },
    { id: 834, display: "Drednaw", thumbnail: "sprites/pokemon/834.png" },
    { id: 835, display: "Yamper", thumbnail: "sprites/pokemon/835.png" },
    { id: 836, display: "Boltund", thumbnail: "sprites/pokemon/836.png" },
    { id: 837, display: "Rolycoly", thumbnail: "sprites/pokemon/837.png" },
    { id: 838, display: "Carkol", thumbnail: "sprites/pokemon/838.png" },
    { id: 839, display: "Coalossal", thumbnail: "sprites/pokemon/839.png" },
    { id: 840, display: "Applin", thumbnail: "sprites/pokemon/840.png" },
    { id: 841, display: "Flapple", thumbnail: "sprites/pokemon/841.png" },
    { id: 842, display: "Appletun", thumbnail: "sprites/pokemon/842.png" },
    { id: 843, display: "Silicobra", thumbnail: "sprites/pokemon/843.png" },
    { id: 844, display: "Sandaconda", thumbnail: "sprites/pokemon/844.png" },
    { id: 845, display: "Cramorant", thumbnail: "sprites/pokemon/845.png" },
    { id: 846, display: "Arrokuda", thumbnail: "sprites/pokemon/846.png" },
    { id: 847, display: "Barraskewda", thumbnail: "sprites/pokemon/847.png" },
    { id: 848, display: "Toxel", thumbnail: "sprites/pokemon/848.png" },
    {
      id: 849,
      display: "Toxtricity-Amped",
      thumbnail: "sprites/pokemon/849.png",
    },
    { id: 850, display: "Sizzlipede", thumbnail: "sprites/pokemon/850.png" },
    { id: 851, display: "Centiskorch", thumbnail: "sprites/pokemon/851.png" },
    { id: 852, display: "Clobbopus", thumbnail: "sprites/pokemon/852.png" },
    { id: 853, display: "Grapploct", thumbnail: "sprites/pokemon/853.png" },
    { id: 854, display: "Sinistea", thumbnail: "sprites/pokemon/854.png" },
    { id: 855, display: "Polteageist", thumbnail: "sprites/pokemon/855.png" },
    { id: 856, display: "Hatenna", thumbnail: "sprites/pokemon/856.png" },
    { id: 857, display: "Hattrem", thumbnail: "sprites/pokemon/857.png" },
    { id: 858, display: "Hatterene", thumbnail: "sprites/pokemon/858.png" },
    { id: 859, display: "Impidimp", thumbnail: "sprites/pokemon/859.png" },
    { id: 860, display: "Morgrem", thumbnail: "sprites/pokemon/860.png" },
    { id: 861, display: "Grimmsnarl", thumbnail: "sprites/pokemon/861.png" },
    { id: 862, display: "Obstagoon", thumbnail: "sprites/pokemon/862.png" },
    { id: 863, display: "Perrserker", thumbnail: "sprites/pokemon/863.png" },
    { id: 864, display: "Cursola", thumbnail: "sprites/pokemon/864.png" },
    { id: 865, display: "Sirfetchd", thumbnail: "sprites/pokemon/865.png" },
    { id: 866, display: "Mr-Rime", thumbnail: "sprites/pokemon/866.png" },
    { id: 867, display: "Runerigus", thumbnail: "sprites/pokemon/867.png" },
    { id: 868, display: "Milcery", thumbnail: "sprites/pokemon/868.png" },
    { id: 869, display: "Alcremie", thumbnail: "sprites/pokemon/869.png" },
    { id: 870, display: "Falinks", thumbnail: "sprites/pokemon/870.png" },
    { id: 871, display: "Pincurchin", thumbnail: "sprites/pokemon/871.png" },
    { id: 872, display: "Snom", thumbnail: "sprites/pokemon/872.png" },
    { id: 873, display: "Frosmoth", thumbnail: "sprites/pokemon/873.png" },
    { id: 874, display: "Stonjourner", thumbnail: "sprites/pokemon/874.png" },
    { id: 875, display: "Eiscue-Ice", thumbnail: "sprites/pokemon/875.png" },
    { id: 876, display: "Indeedee-Male", thumbnail: "sprites/pokemon/876.png" },
    {
      id: 877,
      display: "Morpeko-Full-Belly",
      thumbnail: "sprites/pokemon/877.png",
    },
    { id: 878, display: "Cufant", thumbnail: "sprites/pokemon/878.png" },
    { id: 879, display: "Copperajah", thumbnail: "sprites/pokemon/879.png" },
    { id: 880, display: "Dracozolt", thumbnail: "sprites/pokemon/880.png" },
    { id: 881, display: "Arctozolt", thumbnail: "sprites/pokemon/881.png" },
    { id: 882, display: "Dracovish", thumbnail: "sprites/pokemon/882.png" },
    { id: 883, display: "Arctovish", thumbnail: "sprites/pokemon/883.png" },
    { id: 884, display: "Duraludon", thumbnail: "sprites/pokemon/884.png" },
    { id: 885, display: "Dreepy", thumbnail: "sprites/pokemon/885.png" },
    { id: 886, display: "Drakloak", thumbnail: "sprites/pokemon/886.png" },
    { id: 887, display: "Dragapult", thumbnail: "sprites/pokemon/887.png" },
    { id: 888, display: "Zacian", thumbnail: "sprites/pokemon/888.png" },
    { id: 889, display: "Zamazenta", thumbnail: "sprites/pokemon/889.png" },
    { id: 890, display: "Eternatus", thumbnail: "sprites/pokemon/890.png" },
    { id: 891, display: "Kubfu", thumbnail: "sprites/pokemon/891.png" },
    {
      id: 892,
      display: "Urshifu-Single-Strike",
      thumbnail: "sprites/pokemon/892.png",
    },
    { id: 893, display: "Zarude", thumbnail: "sprites/pokemon/893.png" },
    { id: 894, display: "Regieleki", thumbnail: "sprites/pokemon/894.png" },
    { id: 895, display: "Regidrago", thumbnail: "sprites/pokemon/895.png" },
    { id: 896, display: "Glastrier", thumbnail: "sprites/pokemon/896.png" },
    { id: 897, display: "Spectrier", thumbnail: "sprites/pokemon/897.png" },
    { id: 898, display: "Calyrex", thumbnail: "sprites/pokemon/898.png" },
    { id: 899, display: "Wyrdeer", thumbnail: "sprites/pokemon/899.png" },
    { id: 900, display: "Kleavor", thumbnail: "sprites/pokemon/900.png" },
    { id: 901, display: "Ursaluna", thumbnail: "sprites/pokemon/901.png" },
    {
      id: 902,
      display: "Basculegion-Male",
      thumbnail: "sprites/pokemon/902.png",
    },
    { id: 903, display: "Sneasler", thumbnail: "sprites/pokemon/903.png" },
    { id: 904, display: "Overqwil", thumbnail: "sprites/pokemon/904.png" },
    {
      id: 905,
      display: "Enamorus-Incarnate",
      thumbnail: "sprites/pokemon/905.png",
    },
    { id: 906, display: "Sprigatito", thumbnail: "sprites/pokemon/906.png" },
    { id: 907, display: "Floragato", thumbnail: "sprites/pokemon/907.png" },
    { id: 908, display: "Meowscarada", thumbnail: "sprites/pokemon/908.png" },
    { id: 909, display: "Fuecoco", thumbnail: "sprites/pokemon/909.png" },
    { id: 910, display: "Crocalor", thumbnail: "sprites/pokemon/910.png" },
    { id: 911, display: "Skeledirge", thumbnail: "sprites/pokemon/911.png" },
    { id: 912, display: "Quaxly", thumbnail: "sprites/pokemon/912.png" },
    { id: 913, display: "Quaxwell", thumbnail: "sprites/pokemon/913.png" },
    { id: 914, display: "Quaquaval", thumbnail: "sprites/pokemon/914.png" },
    { id: 915, display: "Lechonk", thumbnail: "sprites/pokemon/915.png" },
    { id: 916, display: "Oinkologne", thumbnail: "sprites/pokemon/916.png" },
    { id: 917, display: "Tarountula", thumbnail: "sprites/pokemon/917.png" },
    { id: 918, display: "Spidops", thumbnail: "sprites/pokemon/918.png" },
    { id: 919, display: "Nymble", thumbnail: "sprites/pokemon/919.png" },
    { id: 920, display: "Lokix", thumbnail: "sprites/pokemon/920.png" },
    { id: 921, display: "Pawmi", thumbnail: "sprites/pokemon/921.png" },
    { id: 922, display: "Pawmo", thumbnail: "sprites/pokemon/922.png" },
    { id: 923, display: "Pawmot", thumbnail: "sprites/pokemon/923.png" },
    { id: 924, display: "Tandemaus", thumbnail: "sprites/pokemon/924.png" },
    { id: 925, display: "Maushold", thumbnail: "sprites/pokemon/925.png" },
    { id: 926, display: "Fidough", thumbnail: "sprites/pokemon/926.png" },
    { id: 927, display: "Dachsbun", thumbnail: "sprites/pokemon/927.png" },
    { id: 928, display: "Smoliv", thumbnail: "sprites/pokemon/928.png" },
    { id: 929, display: "Dolliv", thumbnail: "sprites/pokemon/929.png" },
    { id: 930, display: "Arboliva", thumbnail: "sprites/pokemon/930.png" },
    { id: 931, display: "Squawkabilly", thumbnail: "sprites/pokemon/931.png" },
    { id: 932, display: "Nacli", thumbnail: "sprites/pokemon/932.png" },
    { id: 933, display: "Naclstack", thumbnail: "sprites/pokemon/933.png" },
    { id: 934, display: "Garganacl", thumbnail: "sprites/pokemon/934.png" },
    { id: 935, display: "Charcadet", thumbnail: "sprites/pokemon/935.png" },
    { id: 936, display: "Armarouge", thumbnail: "sprites/pokemon/936.png" },
    { id: 937, display: "Ceruledge", thumbnail: "sprites/pokemon/937.png" },
    { id: 938, display: "Tadbulb", thumbnail: "sprites/pokemon/938.png" },
    { id: 939, display: "Bellibolt", thumbnail: "sprites/pokemon/939.png" },
    { id: 940, display: "Wattrel", thumbnail: "sprites/pokemon/940.png" },
    { id: 941, display: "Kilowattrel", thumbnail: "sprites/pokemon/941.png" },
    { id: 942, display: "Maschiff", thumbnail: "sprites/pokemon/942.png" },
    { id: 943, display: "Mabosstiff", thumbnail: "sprites/pokemon/943.png" },
    { id: 944, display: "Shroodle", thumbnail: "sprites/pokemon/944.png" },
    { id: 945, display: "Grafaiai", thumbnail: "sprites/pokemon/945.png" },
    { id: 946, display: "Bramblin", thumbnail: "sprites/pokemon/946.png" },
    { id: 947, display: "Brambleghast", thumbnail: "sprites/pokemon/947.png" },
    { id: 948, display: "Toedscool", thumbnail: "sprites/pokemon/948.png" },
    { id: 949, display: "Toedscruel", thumbnail: "sprites/pokemon/949.png" },
    { id: 950, display: "Klawf", thumbnail: "sprites/pokemon/950.png" },
    { id: 951, display: "Capsakid", thumbnail: "sprites/pokemon/951.png" },
    { id: 952, display: "Scovillain", thumbnail: "sprites/pokemon/952.png" },
    { id: 953, display: "Rellor", thumbnail: "sprites/pokemon/953.png" },
    { id: 954, display: "Rabsca", thumbnail: "sprites/pokemon/954.png" },
    { id: 955, display: "Flittle", thumbnail: "sprites/pokemon/955.png" },
    { id: 956, display: "Espathra", thumbnail: "sprites/pokemon/956.png" },
    { id: 957, display: "Tinkatink", thumbnail: "sprites/pokemon/957.png" },
    { id: 958, display: "Tinkatuff", thumbnail: "sprites/pokemon/958.png" },
    { id: 959, display: "Tinkaton", thumbnail: "sprites/pokemon/959.png" },
    { id: 960, display: "Wiglett", thumbnail: "sprites/pokemon/960.png" },
    { id: 961, display: "Wugtrio", thumbnail: "sprites/pokemon/961.png" },
    { id: 962, display: "Bombirdier", thumbnail: "sprites/pokemon/962.png" },
    { id: 963, display: "Finizen", thumbnail: "sprites/pokemon/963.png" },
    { id: 964, display: "Palafin", thumbnail: "sprites/pokemon/964.png" },
    { id: 965, display: "Varoom", thumbnail: "sprites/pokemon/965.png" },
    { id: 966, display: "Revavroom", thumbnail: "sprites/pokemon/966.png" },
    { id: 967, display: "Cyclizar", thumbnail: "sprites/pokemon/967.png" },
    { id: 968, display: "Orthworm", thumbnail: "sprites/pokemon/968.png" },
    { id: 969, display: "Glimmet", thumbnail: "sprites/pokemon/969.png" },
    { id: 970, display: "Glimmora", thumbnail: "sprites/pokemon/970.png" },
    { id: 971, display: "Greavard", thumbnail: "sprites/pokemon/971.png" },
    { id: 972, display: "Houndstone", thumbnail: "sprites/pokemon/972.png" },
    { id: 973, display: "Flamigo", thumbnail: "sprites/pokemon/973.png" },
    { id: 974, display: "Cetoddle", thumbnail: "sprites/pokemon/974.png" },
    { id: 975, display: "Cetitan", thumbnail: "sprites/pokemon/975.png" },
    { id: 976, display: "Veluza", thumbnail: "sprites/pokemon/976.png" },
    { id: 977, display: "Dondozo", thumbnail: "sprites/pokemon/977.png" },
    { id: 978, display: "Tatsugiri", thumbnail: "sprites/pokemon/978.png" },
    { id: 979, display: "Annihilape", thumbnail: "sprites/pokemon/979.png" },
    { id: 980, display: "Clodsire", thumbnail: "sprites/pokemon/980.png" },
    { id: 981, display: "Farigiraf", thumbnail: "sprites/pokemon/981.png" },
    { id: 982, display: "Dudunsparce", thumbnail: "sprites/pokemon/982.png" },
    { id: 983, display: "Kingambit", thumbnail: "sprites/pokemon/983.png" },
    { id: 984, display: "Great-Tusk", thumbnail: "sprites/pokemon/984.png" },
    { id: 985, display: "Scream-Tail", thumbnail: "sprites/pokemon/985.png" },
    { id: 986, display: "Brute-Bonnet", thumbnail: "sprites/pokemon/986.png" },
    { id: 987, display: "Flutter-Mane", thumbnail: "sprites/pokemon/987.png" },
    { id: 988, display: "Slither-Wing", thumbnail: "sprites/pokemon/988.png" },
    { id: 989, display: "Sandy-Shocks", thumbnail: "sprites/pokemon/989.png" },
    { id: 990, display: "Iron-Treads", thumbnail: "sprites/pokemon/990.png" },
    { id: 991, display: "Iron-Bundle", thumbnail: "sprites/pokemon/991.png" },
    { id: 992, display: "Iron-Hands", thumbnail: "sprites/pokemon/992.png" },
    { id: 993, display: "Iron-Jugulis", thumbnail: "sprites/pokemon/993.png" },
    { id: 994, display: "Iron-Moth", thumbnail: "sprites/pokemon/994.png" },
    { id: 995, display: "Iron-Thorns", thumbnail: "sprites/pokemon/995.png" },
    { id: 996, display: "Frigibax", thumbnail: "sprites/pokemon/996.png" },
    { id: 997, display: "Arctibax", thumbnail: "sprites/pokemon/997.png" },
    { id: 998, display: "Baxcalibur", thumbnail: "sprites/pokemon/998.png" },
    { id: 999, display: "Gimmighoul", thumbnail: "sprites/pokemon/999.png" },
    { id: 1000, display: "Gholdengo", thumbnail: "sprites/pokemon/1000.png" },
    { id: 1001, display: "Wo-Chien", thumbnail: "sprites/pokemon/1001.png" },
    { id: 1002, display: "Chien-Pao", thumbnail: "sprites/pokemon/1002.png" },
    { id: 1003, display: "Ting-Lu", thumbnail: "sprites/pokemon/1003.png" },
    { id: 1004, display: "Chi-Yu", thumbnail: "sprites/pokemon/1004.png" },
    {
      id: 1005,
      display: "Roaring-Moon",
      thumbnail: "sprites/pokemon/1005.png",
    },
    {
      id: 1006,
      display: "Iron-Valiant",
      thumbnail: "sprites/pokemon/1006.png",
    },
    { id: 1007, display: "Koraidon", thumbnail: "sprites/pokemon/1007.png" },
    { id: 1008, display: "Miraidon", thumbnail: "sprites/pokemon/1008.png" },
    {
      id: 1009,
      display: "Walking-Wake",
      thumbnail: "sprites/pokemon/1009.png",
    },
    { id: 1010, display: "Iron-Leaves", thumbnail: "sprites/pokemon/1010.png" },
    { id: 1011, display: "Dipplin", thumbnail: "sprites/pokemon/1011.png" },
    {
      id: 1012,
      display: "Poltchageist",
      thumbnail: "sprites/pokemon/1012.png",
    },
    { id: 1013, display: "Sinistcha", thumbnail: "sprites/pokemon/1013.png" },
    { id: 1014, display: "Okidogi", thumbnail: "sprites/pokemon/1014.png" },
    { id: 1015, display: "Munkidori", thumbnail: "sprites/pokemon/1015.png" },
    { id: 1016, display: "Fezandipiti", thumbnail: "sprites/pokemon/1016.png" },
    { id: 1017, display: "Ogerpon", thumbnail: "sprites/pokemon/1017.png" },
  ];
};

export { pokemonList };
export type { PokemonListInterface };
